### ISSUE TITLE
How to use the component for dynamically created iron list.

### ISSUE THREAD

**Issue by sumukhj84** [pkaske/i18-n#5]
How i can use this component to localize the dynamically created iron-list or grid?

**Comment by trading-peter** [comment]
I would use the provider mode of <i18-n>. This way you get a object with
the translation strings that can be used with polymers data binding system.
Makes sense?

Von meinem Smartphone gesendet
Am 16.03.2016 9:07 nachm. schrieb "sumukhj84" notifications@github.com:

**Comment by sumukhj84** [comment]
I am excited to use your component. Do you have  any example as i am trying to use your component for internationalization. Also how i can download this component as when i used bower install i18-n --save command it did not install the component.

**Comment by trading-peter** [comment]
You can find an example in the demo folder. To install the component use

bower install --save pkaske/i18-n

Let me now if you need more help.

Von meinem Smartphone gesendet
Am 16.03.2016 9:51 nachm. schrieb "sumukhj84" notifications@github.com:

**Comment by sumukhj84** [comment]
Thanks.
